version: '3.7'
services:
  mariadb:
    image: mariadb:latest
    container_name: matching_db
    environment:
      - MYSQL_ROOT_PASSWORD=root-secret
      - MYSQL_DATABASE=matching.db
      - MYSQL_USER=golang
      - MYSQL_PASSWORD=my-secret-pw
    ports:
      - 33061:3306

  golang:
    build:
      context: ./docker/go
      dockerfile: Dockerfile
    ports:
      - 8080:80
    working_dir: /app
    volumes:
      - ./src:/app